### PR TITLE
Fix use of uninitialized value

### PR DESCRIPTION
**Pull request by Ralender**
in this code path emitted is uninitialized and shouldn't be used.
I don't know if this is the right way to fix it.

### CODE REVIEW

**Comment by keryell** [comment]
Nice catch!
But I am not sure this is the right fix.
I have looked at the code and https://raytracing.github.io/books/RayTracingTheNextWeek.html#rectanglesandlights/addingbackgroundcolortotheraycolorfunction, I wonder whether it should not be initialized to 0 on line https://github.com/triSYCL/path_tracer/blob/main/include/render.hpp#L59 instead.
Perhaps it works with triSYCL because the `sycl::vec` are default initialized to 0 but not in DPC++?
On the other hands, I have tried with and without your fix and the images are exactly the same...
So perhaps your fix is good or the scene does not need the missing feature?

**Review by keryell — COMMENTED** [review]
So more fundamentally, should we have the `vec`, `color` and `point` inherit from `sycl::vec` and have a default constructor to `{0,0,0}` instead of being just a type alias?
Not clear whether this behavior was used outside of the case you found.

**Comment by lforg37** [comment]
> So perhaps your fix is good or the scene does not need the missing feature?

I think the fix is good: 

- The only material type that does not emit all zero color is `lightsource_material`
- But `lightsource_material` doesn't scatter so when a ray intersect an object with this texture, the function returns at [this line](https://github.com/triSYCL/path_tracer/blob/188a228ffc6e017d419a390ea734c6196fdc8582/include/render.hpp#L76)
- In all other cases, emitted will have the value 0 before the next loop step.

**Review by lforg37 — APPROVED** [review]

**Comment by keryell** [comment]
> > So perhaps your fix is good or the scene does not need the missing feature?
> 
> I think the fix is good:
> 
>     * The only material type that does not emit all zero color is `lightsource_material`
> 
>     * But `lightsource_material` doesn't scatter so when a ray intersect an object with this texture, the function returns at [this line](https://github.com/triSYCL/path_tracer/blob/188a228ffc6e017d419a390ea734c6196fdc8582/include/render.hpp#L76)
> 
>     * In all other cases, emitted will have the value 0 before the next loop step.

This is useful information... Should we keep this information somewhere in some comments?
I guess we will run in a problem along our future road trip adding new styles of objects, such as something emitting light and scattering and semi-transparent and...

**Pull request merged**
